{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "language": "android"

env:
 global:
 - ANDROID_API=27
 - EMULATOR_API=25
 - ANDROID_BUILD_TOOLS=27.1.0
- ADB_INSTALL_TIMEOUT=5 # minutes
}
